### ISSUE TITLE
Turns out QSqlDatabase already maintains database connection

### ISSUE THREAD

**Issue by voidash** [PrekshyaDawadi/E-Matdaan#5]
on main.cpp i ran this code `db.connectionName()`
```c++
    QSqlDatabase db = QSqlDatabase::addDatabase("QSQLITE");
    qDebug() << db.connectionName();
```
Ani output chai `qt_sql_default_connection` dincha. Now no need to `addDatabase` again and again. 

aba jun pani file bata i can simply call 
`    db = QSqlDatabase::database("qt_sql_default_connection");` 

Jastai on `mainwindow.cpp`
![image](https://user-images.githubusercontent.com/23181294/162763189-2b3ce110-5cbd-4479-bd26-948858b85bda.png)

**Comment by voidash** [comment]
ani push agi banako database, i can help you showing candidates on `combobox`

**Comment by PrekshyaDawadi** [comment]
> on main.cpp i ran this code `db.connectionName()`
> 
> ```c++
>     QSqlDatabase db = QSqlDatabase::addDatabase("QSQLITE");
>     qDebug() << db.connectionName();
> ```
> 
> Ani output chai `qt_sql_default_connection` dincha. Now no need to `addDatabase` again and again.
> 
> aba jun pani file bata i can simply call ` db = QSqlDatabase::database("qt_sql_default_connection");`
> 
> Jastai on `mainwindow.cpp` ![image](https://user-images.githubusercontent.com/23181294/162763189-2b3ce110-5cbd-4479-bd26-948858b85bda.png)

Eh okkk so now all I need to do is database sanga kaam garne bela add tyo db = QSqlDatabase::database("qt_sql_default_connection"); wala line right?

**Comment by PrekshyaDawadi** [comment]
> ani push agi banako database, i can help you showing candidates on `combobox`

Huncha, maile ahile tesma kei gareko chaina because there's another issue that I'm facing.

**Comment by PrekshyaDawadi** [comment]
> > on main.cpp i ran this code `db.connectionName()`
> > ```c++
> >     QSqlDatabase db = QSqlDatabase::addDatabase("QSQLITE");
> >     qDebug() << db.connectionName();
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Ani output chai `qt_sql_default_connection` dincha. Now no need to `addDatabase` again and again.
> > aba jun pani file bata i can simply call ` db = QSqlDatabase::database("qt_sql_default_connection");`
> > Jastai on `mainwindow.cpp` ![image](https://user-images.githubusercontent.com/23181294/162763189-2b3ce110-5cbd-4479-bd26-948858b85bda.png)
> 
> Eh okkk so now all I need to do is database sanga kaam garne bela add tyo db = QSqlDatabase::database("qt_sql_default_connection"); wala line right?

Update: Added the line and it doesn't show tyo paila dekhako error anymore. 
Thanks!
